Learning-Fuze/C2.17_flash_cards

- skeleton_html/create_deck.html
- skeleton_html/dummydata.js
- skeleton_html/my_shelf.html
- skeleton_html/profile_settings.html
- skeleton_html/returning_user.html
- skeleton_html/sample_card.html
- skeleton_html/search_page.html
- skeleton_html/single_card_study.html
Contains my shelf button and routing for html
> Gasper dev

- client/src/actions/index.js
- client/src/actions/types.js
- client/src/components/my_shelf_td.js
- client/src/components/recent_stacks.js
- client/src/components/stackView_stacks.js
- client/src/reducers/stack_reducer.js
- server/routes/test.js
Axios call urls are currently not the same as what Brian has in his branch? Confusion over how the updated url's did not make it into the branch
> Updated actions, creators, reducers

- client/dist/index.html
- client/src/components/app.js
- client/src/components/appBar/app_bar_with_drawer.js
- client/src/components/appBar/header_nav_links.js
- client/src/components/cardCreation/create_cards.js
- client/src/components/confirmActionModal/confirm.js
- client/src/components/confirmActionModal/deleteCard.js
- client/src/components/confirmActionModal/deleteStack.js
- client/src/components/home/community_stacks.js
- client/src/components/home/home.js
- client/src/components/home/recent_stacks.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/index.js
- routes/users.js
- server/c217_fc.sql
Did inline CSS for Home: Recent and Community stacks; myShelf is styled similarly as well
> More styling

- client/src/components/auth/log_in.js
- client/src/components/auth/registration.js
- client/src/components/cardCreation/create_cards.js
- client/src/components/editCard/add.js
- client/src/components/editCard/edit.js
- client/src/components/search/search_page.js
- client/src/components/utilities/renderInput.js
Made render input its own component. Going to move onto card component
> Render Input utility

- client/src/actions/index.js
- client/src/components/app.js
- client/src/components/cardCreation/create_cards.js
- client/src/components/confirmActionModal/deleteStack.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/profile/profile.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderStackSummary.js
- client/src/components/utilities/stackSummaryStyle.js
- routes/users.js
Pull request prior to going into dev/live
> Styling + Create Cards Routing

- client/src/actions/index.js
- client/src/components/appBar/app_bar_with_drawer.js
- client/src/components/singleCard/single_card.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/reducers/stack_reducer.js
- routes/users.js
Following copying, user is redirected to the stackOverview for their newly copied stack
> Copied redirect

- client/src/components/appBar/app_bar_with_drawer.js
- client/src/components/confirmActionModal/deleteCard.js
- client/src/components/editCard/edit.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderStackSummary.js
- client/src/components/utilities/stackSummaryStyle.js
More of the internal components/pages are now somewhat styled but more work still needs to be done. However, there needs to be an intense focus on the landing page style/styling, e.g. on mobile, I could not access the username field of the login
@Kchalmers  + @stayasleep
> Added styling

- client/src/actions/index.js
- routes/users.js
Removed more console.logs and updated comments in users.js
> Code Styling

- client/src/components/confirmActionModal/deleteCard.js
- client/src/components/editCard/edit.js
- client/src/components/myShelf/my_shelf.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/stackOverview/stack_overview.js
- client/src/components/utilities/stackSummaryStyle.js
> My shelf styling

- client/src/components/home/home.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/search/search_page.js
- client/src/components/singleCard/single_card.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderStackSummary.js
- routes/users.js
Done rapidly so not the most efficient coding style
> Search, home, and single card study mode styling

- client/src/actions/index.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/stackSummaryStyle.js
Styled the cards with some padding. There is now a handle expansion file
> Styling - Gasper

- client/src/actions/index.js
- client/src/components/auth/registration.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderInputReg.js
- routes/users.js
It is working now, and ready to go
> got a response for taken user going

- client/src/actions/index.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/stackOverview.css
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderStackSummary.js
- client/src/components/utilities/stackSummaryStyle.js
> Stack styling

- client/src/actions/index.js
- client/src/components/cardCreation/create_cards.js
- client/src/components/inputComponent.css
- client/src/components/utilities/renderInput.js
- client/src/components/utilities/renderInputReg.js
- client/src/components/utilities/stackSummaryStyle.js
Upped the box shadow to make the cards more visible. 
Made the placeholder text darker
> Input styling + Card Creation

- client/src/actions/index.js
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/stackSummaryStyle.js
The cards on the stackOverview component should not have had a box shadow.
> Fixed stackOverview styling

- client/src/actions/index.js
- client/src/components/stackOverview.css
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/stackSummaryStyle.js
Card grid is now more uniform. Media queries were written that primarily cover portrait mode for most phones.
> Stack Overview: Styling

- client/src/actions/index.js
- client/src/components/add_single_card.css
- client/src/components/appBar/app_bar_with_drawer.js
- client/src/components/editCard/add.js
- client/src/components/editCard/edit.js
- client/src/components/stackOverview.css
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/stackSummaryStyle.js
The add single card form is slightly more mobile responsive but not perfect, and I fixed the nav links so landscape mode would not cause the logout link to jump up the nav bar
> Media queries

- client/src/components/editCard/edit.js
- client/src/components/utilities/renderInput.js
- feedback.md
Form now populates with old question and answer in case the user had a typo and just wanted to edit a single word.
> Stackoverview edit card

- feedback.md
Crossed out the registration updated and the study mode update
> Updated Feedback to Reflect Current Progress

- client/src/components/home.css
- client/src/components/home/recent_stacks.js
- client/src/components/myShelf/my_shelf_td.js
- client/src/components/myshelf.css
- client/src/components/stackOverview.css
- client/src/components/stackOverview/stackView_stacks.js
- client/src/components/utilities/renderInput.js
"Added message for new user that has links to create card. Added message for empty My Shelf message that links to create cards or search cards. Added circular progress component for loading."
> New User - UX Update

- client/src/components/stackOverview.css
Now the icon is teal instead of the entire div.
> Content copy fill color

- client/src/components/appBar/app_bar_with_drawer.js
- client/src/components/auth/about.js
Added the padding and the color Tim pointed out we needed for the About page
> About section now has padding on the text.

- client/src/actions/index.js
Removed the commented out block of code pertaining to the getCard method.
> Removed getCard() commented out code block

- README.md
Markdown syntax requires two spaces to register that there should be a new line, so I added the requisite spacing for each item to appear on its own line.
> Edited spacing for Technologies items

- client/src/actions/index.js
- routes/community.js
- routes/home.js
- routes/search.js
SELECT DISTINCT + filtering of results on server side using indexOf(). Band aid solution. Additionally, users can now search for their own stacks using the search functionality.
> Trimmed the results of the auto complete 

- client/src/actions/index.js
- client/src/components/profile/profile.js
- routes/avatars.js
- routes/index.js
- routes/profile.js
- routes/user.js
> Profile Images Now Served Through URL

- client/src/components/utilities/renderStackSummary.js
Toggled route for live site but did *not* `npm run bundle`
> Added cross origin = anonymous and removed extra space

- client/src/actions/index.js
- client/src/components/profile/profile.js
- routes/profile.js
Formatting now matches what worked for community stacks
> Edited Profile Page
